Spawn:
  Range:
    Minimum: 10
    Maximum: 50
  Duration:
    Minimum: 00:15:00
    Maximum: 00:30:00
  Lifetime: 00:05:00
Leaderboard: 3
Sound:
  Spawn:
    Id: minecraft:block.sniffer_egg.plop
    Source: neutral
    Volume: 1.0
    Pitch: 1.0
  Open:
    Id: minecraft:bock.sniffer_egg.hatch
    Source: neutral
    Volume: 1.0
    Pitch: 1.0
Locations:
  - minecraft:allium
  - minecraft:azure_bluet
  - minecraft:blue_orchid
  - minecraft:cornflower
  - minecraft:dandelion
  - minecraft:closed_eyeblossom
  - minecraft:open_eyeblossom
  - minecraft:lily_of_the_valley
  - minecraft:oxeye_daisy
  - minecraft:poppy
  - minecraft:torchflower
  - minecraft:orange_tulip
  - minecraft:pink_tulip
  - minecraft:red_tulip
  - minecraft:white_tulip
  - minecraft:lilac
  - minecraft:peony
  - minecraft:pitcher_plant
  - minecraft:rose_bush
  - minecraft:sunflower
  - minecraft:sweet_berry_bush
  - minecraft:short_grass
  - minecraft:tall_grass
  - minecraft:fern
  - minecraft:large_fern
