# Override the automatic language setting (none, english, german)
LanguageOverride: none

# Mode how the Easter eggs will spawn (ArmorStand, Item)
Mode: Item

Spawn:
  # Range around a player where an Easter egg may spawn
  Range:
    Minimum: 10
    Maximum: 50
  # Duration between spawning of Easter eggs per player
  Duration:
    Minimum: 00:15:00
    Maximum: 00:30:00
  # Despawn time of an Easter egg
  Lifetime: 00:05:00

Statistic:
  # Amount of players in the leaderboard
  Leaderboard: 5
  # Collecting a multiple of this generates firework and message
  Milestone: 100

# Configuration for the Easter egg rain
Rain:
  # Radius of the rain cloud
  Radius: 8
  # Height offset to the player
  Offset: 30
  # Amount of Easter eggs to rain
  Amount: 20
  # Probability of how many eggs will break during the rain [(1 - Breaking) * Amount = Collectable]
  Breaking: 0.95

Sound:
  # Sound played when an Easter egg spawns
  Spawn:
    Id: minecraft:block.sniffer_egg.plop
    Source: neutral
    Volume: 1.0
    Pitch: 1.0
  # Sound played when opening an Easter egg
  Open:
    Id: minecraft:bock.sniffer_egg.crack
    Source: neutral
    Volume: 1.0
    Pitch: 1.0
  # Sound played when first place is reached
  Leaderboard:
    Id: minecraft:entity.firework_rocket.twinkle_far
    Source: neutral
    Volume: 1.0
    Pitch: 1.0
  # Sound played when an egg breaks
  Break:
    Id: minecraft:entity.turtle.egg_break
    Source: neutral
    Volume: 1.0
    Pitch: 1.0

# Valid blocks for egg spawning
Locations:
  - minecraft:allium
  - minecraft:azure_bluet
  - minecraft:blue_orchid
  - minecraft:cornflower
  - minecraft:dandelion
  - minecraft:closed_eyeblossom
  - minecraft:open_eyeblossom
  - minecraft:lily_of_the_valley
  - minecraft:oxeye_daisy
  - minecraft:poppy
  - minecraft:torchflower
  - minecraft:orange_tulip
  - minecraft:pink_tulip
  - minecraft:red_tulip
  - minecraft:white_tulip
  - minecraft:lilac
  - minecraft:peony
  - minecraft:pitcher_plant
  - minecraft:rose_bush
  - minecraft:sunflower
  - minecraft:sweet_berry_bush
  - minecraft:short_grass
  - minecraft:tall_grass
  - minecraft:fern
  - minecraft:large_fern
